version: '3.8'  # Specify the Docker Compose file version

services:
  server:
    build:
      context: .
    volumes:
      - ./:/var/www/html
    ports:
      - "8090:80"

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_ARBITRARY: 1
